#        image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openai-app
  labels:
    app: openai-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openai-app
  template:
    metadata:
      labels:
        app: openai-app
    spec:
      containers:
      - name: openai-app
        image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /healthz  # Adjust this path if necessary
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10


