apiVersion: apps/v1
kind: Deployment
metadata:
  name: openai-app
  labels:
    app: openai-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openai-app
  template:
    metadata:
      labels:
        app: openai-app
    spec:
      containers:
      - name: openai-app
        image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
        ports:
        - containerPort: 5000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: api-key
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
